export {
	SaudeAldeiaApiError,
	SaudeAldeiaClient,
	type SaudeAldeiaClientOptions,
} from "./client.js";
export {
	DEFAULT_BASE_URL,
	type DiseaseCode,
	DiseaseCodeSchema,
	type DiseaseMetric,
	DiseaseMetricSchema,
	type DiseasesResponse,
	DiseasesResponseSchema,
	EstadoSchema,
	type HighAlertItem,
	HighAlertItemSchema,
	type HighAlertsParams,
	HighAlertsParamsSchema,
	type HighAlertsQuery,
	type HighAlertsResponse,
	HighAlertsResponseSchema,
	type MetadataResponse,
	MetadataResponseSchema,
	MunicipioSchema,
	type RiskIndexItem,
	RiskIndexItemSchema,
	type RiskIndexParams,
	RiskIndexParamsSchema,
	type RiskIndexQuery,
	type RiskIndexResponse,
	RiskIndexResponseSchema,
	type RiskLevel,
	RiskLevelSchema,
} from "./schemas.js";
export { type AgentToolDefinition, getAgentTools } from "./tools.js";
